config/routes.rb
Rails.application.routes.draw do
  #get 'comments/new'
  #get '/comments/new', :to => 'comments#new', :as => :comments
  #resources :comments, :path => ''
  #get 'comments/create'


  mount Ckeditor::Engine => '/ckeditor'
  resources :categories, only: [:index, :show]
  resources :posts
  resources :posts, :shallow => true do
    resources :comments
  end
  #resources :comments

  resources :users, except: [:index]

  get '/session/login', to: 'session#login', as:'login'
  post '/session/login', to: 'session#create'
  get '/session/logout', to: 'session#logout', as:'logout'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness:true
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\.]*((pomona|cmc|hmc|scripps|pitzer))\.edu\z/i
  validates :password, length: {minimum: 6}

  has_many :posts
  has_gravatar

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :delete]

def new
  @user = User.new
end

def create
  @user = User.new(user_params)

  if @user.save
    flash[:notice] = "Successfully created a new user!"
    redirect_to user_path(@user)
  else
    flash[:alert] = "Error creating new user!"
    render 'new'
  end
end

def edit
end

def update
  if @user.update(user_params)
    flash[:notice] = "Successfully updated user!"
    redirect_to users_path(@user)
  else
    flash[:user] = "Error editing user!"
    render 'edit'
  end
end

def show
    @posts = @user.posts
    @posts = Post.search(params[:search])
    @categories = Category.all
end

def destroy
  if current_user.id == @user.id
    flash[:notice] = "Successfully deleted user!"
    redirect_to users_path
  else
    flash[:alert] = "Error deleting user!"
  end
end

private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login?
    !!current_user
  end

  def require_user
    redirect '/session/login' unless current_user
  end
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= "#{pluralize(@user.errors.count, "error")}" %>
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%=f.label :username%><br>
  <%=f.text_field :username, autofocus: true, class: "form-control"%>
</div>

<div class="form-group">
  <%=f.label :email%><br>
  <%=f.email_field :email, autofocus: true, class: "form-control"%>
</div>

<div class="form-group">
  <%=f.label :password%>
  <%=f.password_field :password, class: "form-control"%>
</div>

<%= f.submit "Submit", class: "btn btn-primary btn-lg"%>
<%end%>

app/views/users/edit.html.erb
<div class="banner">
  <div class="login-form">
    <div class="col-sm-offset-4 col-sm-4 col-xs-12">
      <h2>Edit User</h2>
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="banner">
  <div class="login-form">
    <div class="col-sm-offset-4 col-sm-4 col-xs-12">
      <h2>Register</h2>
      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner">
  <div class="user-show">
    <div class="col-sm-12 col-xs-12">
      <div class="settings">
        <%=link_to edit_user_path do%>
          <i class="fa fa-cog fa-2x" aria-hidden="true"></i>
        <%end%>
      </div>
      <%= image_tag @user.gravatar_url(size: 180) %>
      <h2 class="text-center"><%= @user.username %></h2>
      <h4 class="text-center"><%= @user.email %></h4>

  <h1 class="text-center"> Your Posts </h1>
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @posts.each do |post| %>
    <div class="col-xs-6">
      <div class="text-left">
        <h2><%= link_to post_path(post) do%>
          <%= post.title %>
          <%end%>
        </h2>
        <h5><%= post.created_at.strftime('%b %d, %Y') %></h5>
        <h3><%=number_to_currency(post.cost)%></h3>
        <%= image_tag post.image.url(:medium) %>
      </div>
      </div>
      <div class="col-xs-6">
        <div class="text-right">
          <p class=post-body><%= raw(post.body).truncate(358) %></p>
        </div>
        <br>
      </div>
      <% if login?%>
      <div class="text-right">
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default"%>
        <br><br>
        <%= link_to "Delete", post_path(post), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}%>
      </div>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <br></br>
      <%end%>
      <br>
    <% end %>
    </div>
  </div>
</div>