config/routes.rb
Rails.application.routes.draw do
  #get 'comments/new'
  #get '/comments/new', :to => 'comments#new', :as => :comments
  #resources :comments, :path => ''
  #get 'comments/create'


  mount Ckeditor::Engine => '/ckeditor'
  resources :categories, only: [:index, :show]
  resources :posts
  resources :posts, :shallow => true do
    resources :comments
  end
  #resources :comments

  resources :users, except: [:index]

  get '/session/login', to: 'session#login', as:'login'
  post '/session/login', to: 'session#create'
  get '/session/logout', to: 'session#logout', as:'logout'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category, presence: true
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	#belongs_to :user

  validates :message, length: {minimum: 5}, presence: true
  #validates :user_id, presence: true

  def self.search(search)
    if search
        search = search.downcase
        where("lower(title) LIKE ?", "%#{search}%")
    else
      all
    end
  end
  
end

app/models/create_comments.rb
class AddPostIdToComments < ActiveRecord::Migration
  def change
    add_column :comments, :post_id, :integer
    add_index  :comments, :post_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  geocoded_by :address
  after_validation :geocode

  validates :title, :body, :cost, presence: true
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy

  scope :newest, -> {order(created_at: :desc)}
  scope :oldest, -> {order(created_at: :asc)}
  scope :lowToHigh, -> {order(cost: :asc)}
  scope :highToLow, -> {order(cost: :desc)}

  def self.sort_by(sort_param)
    case sort_param
    when 'newest'
      newest
    when 'oldest'
      oldest
    when 'lowToHigh'
      lowToHigh
    when 'highToLow'
      highToLow
    else 
      all
    end
  end

  def self.search(search)
    if search
        search = search.downcase
        where("lower(title) LIKE ?", "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness:true
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\.]*((pomona|cmc|hmc|scripps|pitzer))\.edu\z/i
  validates :password, length: {minimum: 6}

  has_many :posts
  has_gravatar

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

# #New 1
#   def current_user
#   	return unless session[:user_id]
#   	#@current_user ||= User.find(session[:user_id])
#   	@current_user ||= User.find_by_id(params[:user_id]) || User.find_by_id(params[:id])
#   end
# #New 2

  include UsersHelper 


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
#    @comment = @post.comments.create(comment_params)
    @comment = @post.comments.new(comment_params)
    if @comment.save!
      flash[:notice] = "Comment Posted!"
      redirect_to(@post)
    else
      flash[:notice] = "Comment failed"
      redirect_to(@post)
    end
  end

  def comment_params
    #params.require(:comment).permit(:message, :post_id)
    params.require(:comment).permit(:message)
  end
end

app/controllers/posts_controller.rb
# require 'slack-ruby-client'

class PostsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :find_post, only: [:edit, :update, :show, :delete]
  before_action :authenticate, only: [:edit, :update, :destroy]
  
  
  # Slack.configure do |config|
  #   config.token = ENV["SLACK_API_TOKEN"]
  # end
  # client = Slack::Web::Client.new
  # client.auth_test

  def index
    @posts = Post.search(params[:search])
    @categories = Category.all
    #@posts = Post.order(created_at: :desc)
    @posts = Post.sort_by(params[:order])
  end

  def new
    @categories = Category.all
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

   if @post.save
     flash[:notice] = "New post created"
     redirect_to posts_path(@post)
     # client.files_upload(
     #   channels: '#postings',
     #   as_user: true,
     #   file: @post.mage,
     #   title: @post.title,
     #   filename: @post.geocode,
     #   initial_comment: @post.cost
     # )
    else
      flash[:alert] = "Error creating new post"
      render 'new'
    end


  end

  def edit
    @categories = Category.all
    if authenticate
      render 'edit'
    else
      flash[:alert] = "You can only edit your own post"
      redirect_to posts_path
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to posts_path(@post)
    else
      flash[:alert] = "Error updating post"
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if find_post.destroy
      flash[:notice] = "Post deleted"
      redirect_to posts_path
    else
      flash[:alert] = "Error deleting post"
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :cost, :category_id, :image, :longitude, :latitude, :address)
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def authenticate
      @post = Post.find(params[:id])
      current_user.id == @post.user_id
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def login
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successfully logged in!"
      redirect_to posts_path
    else
      flash[:alert] = "Invalid login. Please try again"
      render 'login'
    end
  end

  def logout
    session.clear
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :delete]

def new
  @user = User.new
end

def create
  @user = User.new(user_params)

  if @user.save
    flash[:notice] = "Successfully created a new user!"
    redirect_to user_path(@user)
  else
    flash[:alert] = "Error creating new user!"
    render 'new'
  end
end

def edit
end

def update
  if @user.update(user_params)
    flash[:notice] = "Successfully updated user!"
    redirect_to users_path(@user)
  else
    flash[:user] = "Error editing user!"
    render 'edit'
  end
end

def show
    @posts = @user.posts
    @posts = Post.search(params[:search])
    @categories = Category.all
end

def destroy
  if current_user.id == @user.id
    flash[:notice] = "Successfully deleted user!"
    redirect_to users_path
  else
    flash[:alert] = "Error deleting user!"
  end
end

private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login?
    !!current_user
  end

  def require_user
    redirect '/session/login' unless current_user
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Craigslist</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if login? %>
          <li><%= link_to 'All Posts', posts_path %></li>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'All Categories', categories_path %></li>
          <li><a href="/users/<%=current_user.id%>"><%=current_user.username.capitalize%> </a></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'All Posts', posts_path %></li>
          <li><%= link_to 'All Categories', categories_path %></li>
          <li><%= link_to 'Login', login_path  %></li>
          <li><%= link_to 'Register', new_user_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Craigslist</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%> <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['maps_api_key'] %>">
    </script>
  </head>

  <body>
    <%=render "layouts/navigation"%>
    <div class="container-fluid">
      <%if notice%>
        <p class="notice"><%=notice%></p>
      <%end%>
      <%if alert%>
        <p class="alert"><%=alert%></p>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>